import { Spacing } from '@/constants/theme';
import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingBottom: Spacing.six,
  },
  safeHeader: {
    paddingHorizontal: Spacing.four,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Spacing.two,
  },
  iconButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: 8,
    borderRadius: 20,
  },
  profileInfo: {
    alignItems: 'center',
    marginTop: Spacing.two,
    paddingBottom: Spacing.two,
  },
  avatarRing: {
    padding: 4,
    borderRadius: 56,
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  nameText: {
    color: 'white',
    fontSize: 26,
    fontWeight: '700',
    marginTop: Spacing.three,
    textAlign: 'center',
    paddingHorizontal: Spacing.four,
  },
  numberText: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontSize: 17,
    marginTop: 4,
    letterSpacing: 0.5,
  },
  emailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    paddingHorizontal: Spacing.four,
  },
  emailText: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontSize: 14,
    flexShrink: 1,
  },
  actionRow: {
    flexDirection: 'row',
    gap: Spacing.three,
    marginTop: Spacing.five,
    paddingHorizontal: Spacing.two,
  },
  mainAction: {
    backgroundColor: 'white',
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minWidth: 120,
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 6,
      },
      android: { elevation: 3 },
    }),
  },
  mainActionText: {
    color: '#3c87f7',
    fontWeight: '700',
    fontSize: 16,
  },
  secondaryAction: {
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minWidth: 120,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  secondaryActionText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16,
  },
  content: {
    paddingHorizontal: Spacing.four,
    marginTop: -20,
    paddingBottom: Spacing.six,
  },
  statsRow: {
    flexDirection: 'row',
    gap: Spacing.three,
    marginBottom: Spacing.three,
  },
  statCard: {
    flex: 1,
    padding: Spacing.three,
    borderRadius: 16,
    borderWidth: 1,
    gap: 4,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 4,
      },
      android: { elevation: 1 },
    }),
  },
  card: {
    padding: Spacing.four,
    borderRadius: 20,
    borderWidth: 1,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
    }),
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.three,
  },
  spamBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  spamBadgeText: {
    fontSize: 13,
    fontWeight: '600',
  },
  spamInfo: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 12,
    marginBottom: Spacing.three,
  },
  spamPercent: {
    fontSize: 36,
    fontWeight: '800',
    lineHeight: 40,
  },
  progressBarBg: {
    height: 10,
    borderRadius: 5,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 5,
  },
  section: {
    marginTop: Spacing.five,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.three,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  addTagButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  addTagText: {
    color: '#3c87f7',
    fontWeight: '700',
    fontSize: 14,
  },
  tagsList: {
    gap: Spacing.two,
  },
  tagItem: {
    padding: Spacing.three,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
  },
  tagItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  tagTextBlock: {
    flex: 1,
  },
  tagIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voteButton: {
    backgroundColor: 'rgba(34, 197, 94, 0.12)',
    padding: 8,
    borderRadius: 12,
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voteButtonDisabled: {
    backgroundColor: 'rgba(0, 0, 0, 0.04)',
    opacity: 0.5,
  },
  voteButtonActive: {
    backgroundColor: 'rgba(34, 197, 94, 0.2)',
  },
  emptyTags: {
    padding: Spacing.five,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: 'dashed',
    alignItems: 'center',
    gap: Spacing.two,
  },
  emptyText: {
    textAlign: 'center',
  },
  footerActions: {
    marginTop: Spacing.five,
    marginBottom: Spacing.six,
  },
  blockButton: {
    padding: 16,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    opacity: 0.85,
  },
  blockButtonText: {
    color: '#ef4444',
    fontWeight: '700',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: Spacing.five,
    maxHeight: '75%',
    borderTopWidth: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.four,
  },
  modalEmpty: {
    paddingVertical: Spacing.six,
    alignItems: 'center',
  },
  modalList: {
    paddingBottom: Spacing.five,
  },
  tagOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.three,
    gap: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  tagOptionLabel: {
    fontSize: 17,
    fontWeight: '500',
    flex: 1,
  },
  errorContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.six,
    gap: Spacing.four,
  },
  errorTitle: {
    textAlign: 'center',
    fontSize: 16,
  },
  retryButton: {
    backgroundColor: '#3c87f7',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  retryButtonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16,
  },
});
